export enum ErrorType {
	// General errors
	UNKNOWN = "UNKNOWN",
	UNAUTHORIZED = "UNAUTHORIZED",
	FORBIDDEN = "FORBIDDEN",
	BAD_REQUEST = "BAD_REQUEST",
	NOT_FOUND = "NOT_FOUND",

	// Database errors
	DATABASE_ERROR = "DATABASE_ERROR",
	RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",
	RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

	// Authentication errors
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	TOKEN_EXPIRED = "TOKEN_EXPIRED",
	TOKEN_INVALID = "TOKEN_INVALID",
}
